<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $block->getOrder() ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= /* @escapeNotVerified */ __('Additional Order Information') ?></strong>
    </div>
    <div class="block-content">
        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?= /* @escapeNotVerified */ __('External Order Id') ?>:</span>
            </strong>
            <div class="box-content">
                <?= $block->escapeHtml($_order->getExternalOrderId() ?: __('None')) ?>
            </div>
        </div>
    </div>
</div>
